### ISSUE TITLE
is this project alive? 🙏🏻

### ISSUE THREAD

**Issue by aaalsubaie** [skelpo/capacitor-mapbox#1]
is this project alive? 🙏🏻

**Comment by proggeramlug** [comment]
Define "alive" ;) It is used in production and we do update it sometimes. However, there is only one project that we are currently using for it.

**Comment by aaalsubaie** [comment]
we have a critical react/capacitor project and it depends heavily on mapbox GL js library. it is a bit slow on older devices so your project is like a heaven to us. believe me we dont want to go native :)

should we use it or do you have other recommendations?

**Comment by aaalsubaie** [comment]
I dont see the code by the way...

**Comment by proggeramlug** [comment]
The code is only in NPM, we never pushed the code to Github. The main issue is that our extension is strongly customized for our project, it won't just work out of the box. We did implement Mapbox natively though and so with our extension the map runs natively within ionic. You can check out the app here: https://yourmobileguide.com/

**Comment by aaalsubaie** [comment]
thanks for the clarification and good luck in your project.
